### ISSUE TITLE
✅9월 21일 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#126]
🦆 건주

- [x] SearchInput, SubmitInput 변경
- [x] 연필화질변경
- [x] 메타이미지 만들기
- [x] MyCommunity 오류 수정
- [x] 댓글삭제 리로드없이로 수정
- [x] PostPage 검색기능 오류 수정
- [ ] 야무쌤 답변보고 theme 수정해보기
- [x] 유효성검사는 다 된것같아 완료로 옮겼습니다
- [x] 이미지 최적화 후 코드 변경

  
  
🐶 남진  

- [x] 웹접근성, 아리아라벨

🐰 수연

- [x] 검색 메타 태그
- [x] 성능개선 전 검사 완료하기
- [x] 이미지 최적화 변경

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/8d9acc2b-cf90-430e-b9af-a248a7d679e1)

**Comment by JOSuYeoM** [comment]
힘둘다 ............... 벌써 목요일
