### ISSUE TITLE
✅ 9월 22일 Todo

### ISSUE THREAD

**Issue by JOSuYeoM** [FRONTENDSCHOOL6/escape12#140]
공식적인 프로젝트 마지막 날입니다!!!! 
다들 아자아자 파이팅 🪄🪄🪄😎

**Comment by JOSuYeoM** [comment]
📌✌🏻✌🏻✌🏻✌🏻✌🏻
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/972ddb8f-6ef9-497f-bc52-96ac884d221f)

**Comment by KIMGEUNDU** [comment]
- [ ] 각 페이지 별 useQuery로 코드 변경
- [ ] 채팅창 스타일 수정
- [ ] 채팅창 이미지 조건부 수정

**Comment by JOSuYeoM** [comment]
- [ ] 각 페이지 별 웹 성능 측정 및 개선

**Comment by KIMGEUNDU** [comment]
- [ ] 각 페이지 별 useQuery로 코드 변경

**Comment by skawls** [comment]
- [x] 각 페이지 별 useQuery로 코드 변경
- [ ] postlist ul,li태그로 변경
- [ ] commentpage useQurey > useEffect로 다시 변경
