### ISSUE TITLE
✅ 9월 23, 24일 Todo

### ISSUE THREAD

**Issue by JOSuYeoM** [FRONTENDSCHOOL6/escape12#160]
### ✅ 9월 23일 토요일 - 13시 회의
- [x] 컴포넌트 분리 - mypage...... 오류 범벅돼요ㅠ 도와주세요
- [x] PPT 작업 - 대충 반이상은 만들어놨습니다!
- chat 컴포넌트 중 chanInput 오타 있습니다 !  -> 확인

### ✅ 9월 24일 일요일 - 14시 회의
- [x] main으로 보내고 주석 제거, 정렬
- [x] ppt 완성
- [x] 코드 수정? 질의응답 
- [x] 최종 배포
- [x] 느낀점 각자 작성 (readme 용 길게~)
- [x] 리드미 완성
- [x] 댓글 , 글, 기록 등 룰루랄라 작성하기 -오후로 미루기 !!! 아직 코드 작업 중

**Comment by skawls** [comment]
### ✅ 9월 23일 토요일 - 13시 회의
- [ ] ERD 수정
- [ ] PPT 작성

**Comment by KIMGEUNDU** [comment]
- [ ] theme 페이지 오류 수정
- [ ] theme 페이지 스크롤이벤트 조건문 처리
- [ ] 채팅 모바일 지원
- [ ] uploadRecord 컴포넌트 분리

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/90012060-f98d-4e19-9b83-2172d9b772da)

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/fd707c13-629e-4717-ae7d-be9bbdd92807)

**Comment by JOSuYeoM** [comment]
좋아요\~!
