### ISSUE TITLE
✅ 9월 11일 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#46]
- [ ] 즐겨찾기 데이터 추가 
안되서 가장 마지막으로 미룸 -> 지식이슈
- [x] 기록하기버튼 클릭 시 해당 아이디값만 볼수있는 페이지이동
- [x] 필요한 콜렉션 별 필드 정리

**Comment by skawls** [comment]
-[] 포켓호스트 댓글 업로드 및 가져오기

**Comment by JOSuYeoM** [comment]
- [ ] NotePage.jsx 스타일링 완성
- [ ] add,edit,my,note 반응형 변경 및 확인
- [ ] 포켓호스트
