### ISSUE TITLE
✅ 9월 12일 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#53]
- [ ] ERD 다시 생각해보고 포켓호스트 맞추기 -> 기능구현하면서 릴레이션이 복잡함...
- [x] 라우터 레이아웃 나누기
- [x] 만든 페이지 반응형 맞추기
- [x] 로그인된 사용자만 들어갈 수 있는 페이지 완성
- [x] 로그인시 해당 닉네임으로 환영합니다 메세지
- [x] 갑자기 로그인이 안되는 오류 수정 -> 해결!!!

**Comment by JOSuYeoM** [comment]
- [ ] note 페이지 화면 조정
- [ ] my, edit, note, add 페이지 UI 수정

- [ ] 가능하면 포켓호스트 😥

**Comment by skawls** [comment]
- [ ] 포켓호스트!!!!!!!!!!!!!!!!!
- [ ] 만든 페이지 반응형
