### ISSUE TITLE
✅9월 14일 Todo

### ISSUE THREAD

**Issue by skawls** [FRONTENDSCHOOL6/escape12#59]
- [x] postpage , commentpage 닉네임 표시
- [x] commentpage 에서 댓글 표시 (각 게시글 마다)
- [x] isLoading 로딩중 postpage 넣기
- [x] Nav버튼 이미지로 변경 하기

**Comment by KIMGEUNDU** [comment]
- [ ] 13:00 - 13:25 트러블슈팅방이동

**Comment by KIMGEUNDU** [comment]
수연님 recordPage에 날짜 부분 <Sup>날짜</Sup> 으로 변경해주시고 input에 required 넣어주세용! 데이터 불러오면서 보니까 필요합니다!



![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/a4b2cb00-af4c-47f7-84f7-1aa965f7c491)

**Comment by JOSuYeoM** [comment]
넵!!!

**Comment by JOSuYeoM** [comment]
불러오기!!!!!!!!!!!!!!!⭐⭐⭐
- [ ] - [ ] 내가 작성한 기록 수
- [ ] 내가 작성한 커뮤니티 글 수
- [ ] 내가 작성한 댓글 수

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/d14a27b3-624e-4d37-90ab-7d54811818c5)

저희 컴포넌트가 이제 너무 많아져서 폴더 분리해놨습니다. 머지할 때 다 변경되지않을까싶어요

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/081a0255-c4b6-45ac-b73c-db67bb186648)

남진님 저희 기록버튼이랑 업버튼 디자인변경하고 HeaderRecord 컴포넌트 만들고 PlusNav지우고 UpNav코드 수정했습니다. 병합할때 합쳐질꺼같긴한데 말씀하시면 바로 코드드리겠습니다

**Comment by KIMGEUNDU** [comment]
남진님 저희 스크린크기 변경하는거 어떻게 생각하시나요 320px 은 너무 작아서 그거 맞추다가 디자인이 다 깨지는것같습니다. 그래서
s: 380px~ 이렇게 바꾸기만 하면 될것같아서요 
보시면 의견 말씀해주세용!
