### ISSUE TITLE
⭐ 9월 19일 기능구현 및 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#63]
**저희해야할 기능이 너무 많으니까 각자 맡은 페이지에 들어가야될 기능 정리해서 하나씩 지워가면서 합시당**

📢 11:00 ~ 11:25 트러블슈팅방 이동
🦆 페이지네이션 여쭤보고싶습니다
일단 저희가 구현하기로 계획했던거는 전부 구현한 것 같고 내일부터 컴포넌트 나누기, 성능(특히 useState는 성능에 취약함), 코드수정, 웹접근성, 이미지최적화해야합니당!

📢 저녁에 병합 후 2차배포!

📢 2차배포 후 다른 사람페이지에서 수정할 부분 찾아보기

📢 성능검사는 배포후에 하는게 정확할것같습니다

📢 전체

- [ ] 인피니티스크롤, 페이지네이션
- [x] 툴팁
- [x] 테마모드 전환
- [x] 회원탈퇴 기능
- [x] 좋아요 기능

**Comment by KIMGEUNDU** [comment]
🔧 필수 기능
- [ ]  UploadRecord 데이터 수정
- [ ] MyRecord 나의 기록 불러오기
- [ ] MyRecord에 기록 하나 누르면 해당 아이디값에 대한 페이지 나오게 하기
- [ ] Theme 즐겨찾기 기능
- [ ] LoginSelete 카카오톡로그인, 구글로그인
- [ ] Login ID/PW 찾기


🪛 옵션 기능 
- [ ] Theme 등록하기 
- [ ] Nav기록이 나의 기록 모음이 아니라 다른 사용자의 기록까지 모아놓고 볼 수있도록 만들기
- [ ] 기록모아보기 성공하면 각 기록마다 좋아요기능 및 댓글 기능
- [ ] 기록모아보기에서 원하는 테마의 기록만 볼수있도록 검색기능
- [ ] Theme 상세보기 모달창, 지도API 활용

**Comment by JOSuYeoM** [comment]
### 😮수연

기록 

- [ ]  기록 전체 →내보내기

커뮤니티

- [ ]  아이디, 닉네임 → 불러오기

마이페이지

- [ ]  아이디, 닉네임 → 불러오기
- [ ]  작성한 기록, 커뮤니티 글, 댓글 → 각각 불러오기
- [ ]  즐겨찾기 바로가기는 링크만

정보 변경

- [ ]  아이디, 비밀번호, 닉네임, 사진 변경
- [ ]  정보 변경 후 →내보내기

**Comment by JOSuYeoM** [comment]
### 🤩남진

커뮤니티- 전체 글

- [ ]  ~~제목, 작성자, 커뮤글 → 불러오기~~
- [ ]  검색어 찾기

커뮤니티- 커뮤 클릭 시

- [ ]  작성자, 글 → 불러오기
- [ ]  작성자, 글 수정/삭제
- [ ]  각 글의 댓글 불러오기, 댓글 작성하기

내가 쓴 커뮤글

- [ ]  제목, 작성자, 커뮤글 → 불러오기

내가 쓴 댓글

- [ ]  댓글 → 불러오기
- [ ]  댓글 수정/삭제

**Comment by KIMGEUNDU** [comment]
✅ 전체 div에 붙여넣기
```
bg-light-ec1 dark:bg-dark-ec4 text-light-ec4 dark:text-dark-ec1 text-lg
```

✅ 남진님 저희 text-lg를 기본폰트로 하기로 정했었습니다!

✅ 그리고 버튼이나 검색input 그림자없는게 깔끔한것같습니다.

**Comment by JOSuYeoM** [comment]
아하! 저도 그림자 없는 게 깔끔한 것 같습니다! 좋아여~
