### ISSUE TITLE
✅ 9월 15일 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#68]
📢 수연님 뒤로가기 버튼 이 코드 써보셨나요?
```
<Headerback
	onClick={() => {
		navigate(-1);
	}}
>
```
이 코드쓰면 이전 페이지로 잘 넘어갑니다.

📢 수연님 AddCommunity에 작성자 아이디도 같이 create 되게 해주셔야 남진님이 불러올수있습니다!

📢 등록, 수정, 삭제 등등 이벤트 일어날 시 토스트로 안내문구 해주세용

📢 반응형 바꿔주세요

```
			s: { min: '375px', max: '640px' },
			m: { min: '641px', max: '1279px' },
			l: { min: '1280px' },
```

📢 배포하면서 발견한 문제점
**EditPage에 import문 headerBack -> headerback 으로 변경**

**jsconfig.json 변경**
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*" : ["src/*"]
    }
  }
}
```

**vite.config.js 변경**

```
import react from '@vitejs/plugin-react';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import { env } from 'node:process';
import viteImagemin from '@vheemstra/vite-plugin-imagemin';
import imageminGifSicle from 'imagemin-gifsicle';
import imageminMozjpeg from 'imagemin-mozjpeg';
import imageminPngQuant from 'imagemin-pngquant';
import imageminSvgo from 'imagemin-svgo';
import imageminWebp from 'imagemin-webp';
import { splitVendorChunkPlugin } from 'vite';

const isDev = env.NODE_ENV === 'development';

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		react(),
		splitVendorChunkPlugin(),
		viteImagemin({
			plugins: {
				jpg: imageminMozjpeg(),
				png: imageminPngQuant(),
				gif: imageminGifSicle(),
				svg: imageminSvgo(),
			},
			makeWebp: {
				plugins: {
					jpg: imageminWebp(),
					png: imageminWebp(),
				},
			},
		}),
	],
	css: {
		devSourcemap: true,
		modules: {
			generateScopedName: isDev
				? '[name]_[local]__[hash:base64:5]'
				: '[hash:base64:4]',
		},
	},
	resolve: {
		alias: {
			'@': resolve(__dirname, './src'),
		},
	},
	// 빌드 시, 청크 파일 생성 매뉴얼 구성
	build: {
		rollupOptions: {
			output: {
				manualChunks: {
					react: ['react', 'react-dom'],
					reactRouter: ['react-router-dom'],
					animations: ['gsap'],
				},
			},
		},
	},
});

```

- [x] 6시 1차 배포 -> https:만 수정하면 오류없음!

**Comment by KIMGEUNDU** [comment]
- [ ] 기록버튼 들어간 HeaderBack 만들기
- [ ] theme 즐겨찾기 기능
- [ ] theme 검색기능 꽃길, 풀길, 흙길 추가

**Comment by JOSuYeoM** [comment]
```
<Headerback
	onClick={() => {
		navigate(-1);
	}}
>
```
원래 이 코드를 사용했었는데
기능상 정해진 페이지로 뒤로 가는 게 맞는 것 같아서 
navigate에 다시 주소를 지정해뒀습니다!😎

**Comment by JOSuYeoM** [comment]
이번 주 일요일까지 목표 ㅠㅠ

- [ ] 전체 뒤로가기 경로 수정 : 페이지 주소-> (-1)
- [ ] 마이페이지: 불러온 갯수 클릭 시 해당 링크로 이동
- [ ] 마이페이지: 내가 작성한 기록/글/댓글-> 아이디마다 불러오기
- [ ] 마이페이지: 사진 불러오기
- [ ] 정보 수정: 아이디, 비밀번호, 닉네임 ,사진 기본값 불러오기
- [ ] 정보 수정: 불러온 값에서 원하는 걸로 변경 후 저장
- [ ] toast 기능 추가
