### ISSUE TITLE
✅ 9월 16일, 9월 17일 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#79]
📢 수연님 이미지 제가 다 바꿨습니다!

- [x] **8시 병합**

**Comment by KIMGEUNDU** [comment]
- [ ]  RecordCommunity 닉네임으로는 검색이 안됨
- [ ]  theme 즐겨찾기 이번엔 꼭 성공해보자
- [ ] 즐겨찾기 성공하면 각 게시물 좋아요 기능

**Comment by JOSuYeoM** [comment]
#### edit page
1. 정보 자동으로 불러오기 (사진, 아이디, 비번, 닉네임)
2. 원하는 정보로 수정하기
3. 수정한 상태로 저장되기

- [ ] 리드미 조금씩 작성

**Comment by skawls** [comment]
- [ ] EditCommunity 생성 및 구현
- [ ] MyCommunity > 각 아이디 별로 내가 쓴 게시물 불러오기
- [ ] Mycommunity > 게시글 클릭했을때 해당 페이지로 이동하기
- [ ] Mycomment > 각 아이디별로 내가 쓴 댓글 불러오기
- [ ] Mycommunity > 게시글 클릭했을때 해당 페이지로 이동하기

**Comment by skawls** [comment]
오 신기하네
메일 가나요?
