### ISSUE TITLE
✅ 9월 18일 Todo

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#89]
### 📢 수연님 점심먹기전에 저랑 남진님 병합 한번 했습니다!

**Comment by JOSuYeoM** [comment]
- [ ] 정보 수정 사진 불러오기
- [ ] 사진 변경 기능
- [ ] 사진 스타일 적용
- [ ] 즐겨찾기 링크 걸기-> 건주님 성공 !!!!😎

**Comment by JOSuYeoM** [comment]
### 🔖점심 먹기 전 1차 병합

**Comment by KIMGEUNDU** [comment]
- [ ] 페이지네이션
- [ ] 관리자 계정으로만 테마등록 가능

**Comment by skawls** [comment]
- [ ] post 프로필 사진 가져오기
- [ ] 게시글 호버
- [ ] mycomment - record api 연결
- [ ] [id값에 따른 수정,삭제 버튼 hidden 조건문
